export const regionState = {
  Bhopal: ["Chhattisgarh", "Madhya Pradesh", "Orissa"],
  Lucknow: ["Uttarakhand", "Uttar Pradesh"],
  Chandigarh: [
    "Chandigarh",
    "Himachal Pradesh",
    "Jammu & Kashmir",
    "Ladakh",
    "Punjab",
  ],
  Shillong: [
    "Arunachal Pradesh",
    "Assam",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Sikkim",
    "Tripura",
  ],
  Pune: [
    "Dadra & Nagar Haveli",
    "Daman & Diu",
    "Goa",
    "Gujarat",
    "Maharashtra",
  ],
  Patna: ["Bihar", "Jharkhand", "West Bengal"],
  Hyderabad: [
    "Andhra Pradesh",
    "Andaman and Nicobar Islands",
    "Karnataka",
    "Kerala",
    "Lakshadweep",
    "Pondicherry",
    "Telangana",
  ],
  Jaipur: ["Delhi", "Haryana", "Rajasthan"],
};

export const jnvState = {
  Chhattisgarh: [
    "JNV Dantewada",
    "JNV Dhamtari",
    "JNV Sukma-1",
    "JNV Sukma-2",
    "JNV Durg",
    "JNV Gariyaband",
    "JNV Janjgir Champa",
    "JNV Jashpur",
    "JNV Kabirdham",
    "JNV Kanker",
    "JNV Kondagaon",
    "JNV Korba",
    "JNV Mahasamund",
    "JNV Mungeli",
    "JNV Narayanpur",
    "JNV Raigarh",
    "JNV Balod",
    "JNV Raipur",
    "JNV Rajnandgaon",
    "JNV Surajpur",
    "JNV Surguja",
    "JNV Bilaspur",
    "JNV Balodabazar",
    "JNV Balrampur",
    "JNV Bastar",
    "JNV Bemetara",
    "JNV Bijapur",
    "JNV Korea",
  ],
  "Madhya Pradesh": [
    "JNV Mandla",
    "JNV Mandsaur",
    "JNV Morena",
    "JNV Narsinghpur",
    "JNV Agar Malwa",
    "JNV Neemuch",
    "JNV Panna",
    "JNV Raisen",
    "JNV Rajgarh",
    "JNV Ratlam-1",
    "JNV Ratlam-2",
    "JNV Rewa",
    "JNV Sagar",
    "JNV Satna",
    "JNV Sehore",
    "JNV Seoni",
    "JNV Shajapur",
    "JNV Sheopur",
    "JNV Shivpuri",
    "JNV Sidhi",
    "JNV Tikamgarh",
    "JNV Ujjain-1",
    "JNV Ujjain-2",
    "JNV Umaria",
    "JNV Vidisha",
    "JNV Singrauli",
    "JNV Shahdol",
    "JNV Alirajpur",
    "JNV Anuppur",
    "JNV Ashoknagar",
    "JNV Balaghat",
    "JNV Barwani",
    "JNV Betul",
    "JNV Bhind",
    "JNV Bhopal",
    "JNV Burhanpur",
    "JNV Chhatarpur",
    "JNV Chhindwara",
    "JNV Damoh",
    "JNV Datia",
    "JNV Dewas",
    "JNV Dhar",
    "JNV Dindori",
    "JNV Guna",
    "JNV Gwalior",
    "JNV Harda",
    "JNV Hoshangabad",
    "JNV Indore",
    "JNV Jabalpur",
    "JNV Jhabua-1",
    "JNV Jhabua-2",
    "JNV Katni",
    "JNV Khandwa",
    "JNV Khargone",
  ],
  Orissa: [
    "JNV Balasore",
    "JNV Bargarh",
    "JNV Bhadrak",
    "JNV Bolangir",
    "JNV Boudh",
    "JNV Cuttack",
    "JNV Deogarh",
    "JNV Dhenkanal",
    "JNV Gajapati",
    "JNV Ganjam",
    "JNV Jagatsinghpur",
    "JNV Jajpur",
    "JNV Jharsuguda",
    "JNV Kalahandi",
    "JNV Kendrapara",
    "JNV Keonjhar",
    "JNV Khordha",
    "JNV Koraput",
    "JNV Malkangiri-1",
    "JNV Malkangiri-2",
    "JNV Mayurbhanj",
    "JNV Nabarangpur",
    "JNV Nayagarh",
    "JNV Nuapada",
    "JNV Phulbani",
    "JNV Puri",
    "JNV Rayagada",
    "JNV Sambalpur",
    "JNV Sonepur",
    "JNV Sundargarh",
    "JNV Angul",
  ],
  Uttarakhand: [
    "JNV Almora",
    "JNV Bageshwar",
    "JNV Chamoli",
    "JNV Champawat",
    "JNV Dehradun",
    "JNV Haridwar",
    "JNV Nainital",
    "JNV Pauri Garhwal",
    "JNV Pithoragarh",
    "JNV Rudraprayag",
    "JNV Tehri Garhwal",
    "JNV Udham Singh Nagar",
    "JNV Uttarkashi",
  ],
  "Uttar Pradesh": [
    "JNV Agra",
    "JNV Aligarh",
    "JNV Ambedakar Nagar",
    "JNV Amethi",
    "JNV Auraiya",
    "JNV Azamgarh",
    "JNV Baghpat",
    "JNV Ballia",
    "JNV Balrampur",
    "JNV Banda",
    "JNV Barabanki",
    "JNV Bareilly",
    "JNV Basti",
    "JNV Bharaich",
    "JNV Bijnor",
    "JNV Budaun",
    "JNV Bulandshahr",
    "JNV Chandauli",
    "JNV Chitrakoot",
    "JNV Deoria",
    "JNV Etah",
    "JNV Etawah",
    "JNV Faizabad",
    "JNV Farrukhabad",
    "JNV Fatehpur",
    "JNV Firozabad",
    "JNV Gb Nagar",
    "JNV Ghaziabad",
    "JNV Ghazipur",
    "JNV Gonda",
    "JNV Gorakhpur",
    "JNV Hamirpur",
    "JNV Hardoi",
    "JNV Hathras",
    "JNV Jalaun",
    "JNV Jaunpur",
    "JNV Jhansi",
    "JNV Jpnagar",
    "JNV Kannauj",
    "JNV Kanpur Dehat",
    "JNV Kanpur Nagar",
    "JNV Kasganj",
    "JNV Kaushambi",
    "JNV Kushinagar",
    "JNV Lakhimpur Kheri",
    "JNV Lalitpur",
    "JNV Lucknow",
    "JNV Maharajganj",
    "JNV Mahoba",
    "JNV Mainpuri",
    "JNV Mathura",
    "JNV Mau",
    "JNV Meerut",
    "JNV Mirzapur",
    "JNV Moradabad",
    "JNV Muzaffarnagar",
    "JNV Pilibhit",
    "JNV Pratapgarh",
    "JNV Prayagraj",
    "JNV Raebareli",
    "JNV Rampur",
    "JNV Saharanpur",
    "JNV Sambhal",
    "JNV Santkabir Nagar",
    "JNV Shahjahanpur",
    "JNV Shamli",
    "JNV Shravasti",
    "JNV Siddharth Nagar",
    "JNV Sitapur-1",
    "JNV Sitapur-2",
    "JNV Sonbhadra",
    "JNV Bhadohi",
    "JNV Unnao",
    "JNV Varanasi",
  ],
  Chandigarh: ["JNV Chandigarh"],
  "Himachal Pradesh": [
    "JNV Lahaul Spiti",
    "JNV Mandi",
    "JNV Shimla",
    "JNV Sirmaur",
    "JNV Solan",
    "JNV Una",
    "JNV Bilaspur",
    "JNV Chamba",
    "JNV Hamirpur",
    "JNV Kangra",
    "JNV Kullu",
    "JNV Kinnaur",
  ],
  "Jammu & Kashmir": [
    "JNV Ramban",
    "JNV Reasi",
    "JNV Samba",
    "JNV Shopian",
    "JNV Udhampur",
    "JNV Kulgam",
    "JNV Anantnag",
    "JNV Baramulla",
    "JNV Budgam",
    "JNV Doda",
    "JNV Ganderbal",
    "JNV Jammu-1",
    "JNV Jammu-2",
    "JNV Kathua",
    "JNV Kishtwar",
    "JNV Kupwara",
    "JNV Poonch",
    "JNV Rajouri",
    "JNV Pulwama",
    "JNV Bandipora",
  ],
  Ladakh: ["JNV Kargil", "JNV Leh"],
  Punjab: [
    "JNV Faridkot",
    "JNV Fatehgarh Sahib",
    "JNV Fazilka",
    "JNV Ferozepur",
    "JNV Hoshiarpur",
    "JNV Jallandhar",
    "JNV Kapurthala",
    "JNV Ludhiana",
    "JNV Mansa",
    "JNV Moga",
    "JNV Mohali",
    "JNV Muktsar",
    "JNV Pathankot",
    "JNV Patiala",
    "JNV Ropar",
    "JNV Sangrur",
    "JNV Sbs Nagar",
    "JNV Tarn Taran",
    "JNV Gurdaspur",
    "JNV Amritsar",
    "JNV Barnala",
    "JNV Amritsar-2",
    "JNV Bathinda",
  ],
  "Arunachal Pradesh": [
    "JNV Anjaw",
    "JNV Changlang",
    "JNV Dibang Valley",
    "JNV East Kameng",
    "JNV East Siang",
    "JNV Kurung Kumey",
    "JNV Tirap",
    "JNV Lower Dibang Valley",
    "JNV Lower Subansiri",
    "JNV Lohit",
    "JNV Papumpare",
    "JNV Tawang",
    "JNV Upper Siang",
    "JNV Upper Subansiri",
    "JNV West Kameng",
    "JNV West Siang",
  ],
  Assam: [
    "JNV Baksa",
    "JNV Barpeta",
    "JNV Sonitpur",
    "JNV Bongaigaon",
    "JNV Cachar",
    "JNV Chirang",
    "JNV Darrang",
    "JNV Dhemaji",
    "JNV Dhubri",
    "JNV Dibrugarh",
    "JNV N.C.Hills",
    "JNV Goalpara",
    "JNV Golaghat",
    "JNV Hailakandi",
    "JNV Jorhat",
    "JNV Kamrup",
    "JNV Karbi Anglong-1",
    "JNV Karbi Anglong-2",
    "JNV Karimganj",
    "JNV Kokrajhar",
    "JNV Lakhimpur",
    "JNV Morigaon",
    "JNV Nagaon",
    "JNV Nalbari",
    "JNV Sibsagar",
    "JNV Tinsukia",
    "JNV Udalguri",
  ],
  Manipur: [
    "JNV Senapati-1",
    "JNV Bishnupur",
    "JNV Chandel",
    "JNV Churachandpur",
    "JNV Imphal East",
    "JNV Imphal West",
    "JNV Senapati-2",
    "JNV Tamenglong",
    "JNV Thoubal",
    "JNV Ukhrul-1",
    "JNV Ukhrul-2",
  ],
  Meghalaya: [
    "JNV West Jaintia Hills",
    "JNV East Jaintia Hills",
    "JNV East Khasi Hills-1",
    "JNV East Garo Hills",
    "JNV West Garo Hills",
    "JNV South Garo Hills",
    "JNV Ribhoi",
    "JNV East Khasi Hills-2",
    "JNV West Khasi Hills",
  ],
  Mizoram: [
    "JNV Mamit",
    "JNV Serchip",
    "JNV Champhai",
    "JNV Kolasib",
    "JNV Lawngtlai",
    "JNV Lunglei",
    "JNV Saiha",
    "JNV Aizawl",
  ],
  Nagaland: [
    "JNV Phek",
    "JNV Tuensang",
    "JNV Wokha",
    "JNV Zunheboto",
    "JNV Dimapur",
    "JNV Kiphire",
    "JNV Kohima",
    "JNV Longleng",
    "JNV Mokokchung",
    "JNV Mon",
    "JNV Peren",
  ],
  Sikkim: [
    "JNV West Sikkim",
    "JNV East Sikkim",
    "JNV North Sikkim",
    "JNV South Sikkim",
  ],
  Tripura: [
    "JNV South Tripura",
    "JNV Sepahijala",
    "JNV North Tripura",
    "JNV Khowai",
    "JNV Gomati",
    "JNV Dhalai",
    "JNV West Tripura",
  ],
  "Dadra & Nagar Haveli": ["JNV Silvassa"],
  "Daman & Diu": ["JNV Diu", "JNV Daman"],
  Goa: ["JNV North Goa", "JNV South Goa"],
  Gujarat: [
    "JNV Anand",
    "JNV Aravalli",
    "JNV Banaskantha",
    "JNV Bharuch",
    "JNV Bhavnagar",
    "JNV Botad",
    "JNV Dahod-1",
    "JNV Dahod-2",
    "JNV Dang",
    "JNV Devbhumi Dwarka",
    "JNV Gandhinagar",
    "JNV Gir Somnath",
    "JNV Jamnagar",
    "JNV Kheda",
    "JNV Ahmedabad",
    "JNV Mahisagar",
    "JNV Mehsana",
    "JNV Narmada",
    "JNV Navsari",
    "JNV Panchmahal",
    "JNV Patan",
    "JNV Porbandar",
    "JNV Rajkot",
    "JNV Sabarkantha",
    "JNV Surendranagar",
    "JNV Tapi",
    "JNV Vadodara",
    "JNV Junagadh",
    "JNV Valsad",
    "JNV Kutch",
    "JNV Amreli",
  ],
  Maharashtra: [
    "JNV Sindhudurg",
    "JNV Ahmednagar",
    "JNV Akola",
    "JNV Beed",
    "JNV Bhandara",
    "JNV Chandrapur",
    "JNV Dhule",
    "JNV Gadchiroli",
    "JNV Gondia",
    "JNV Hingoli",
    "JNV Jalgaon",
    "JNV Jalna",
    "JNV Kolhapur",
    "JNV Latur",
    "JNV Nagpur",
    "JNV Nanded",
    "JNV Nandurbar-1",
    "JNV Nandurbar-2",
    "JNV Nasik",
    "JNV Osmanabad",
    "JNV Thane",
    "JNV Parbhani",
    "JNV Pune",
    "JNV Raigad",
    "JNV Ratnagiri",
    "JNV Sangli",
    "JNV Satara",
    "JNV Solapur",
    "JNV Wardha",
    "JNV Amravati",
    "JNV Buldana",
    "JNV Aurangabad",
    "JNV Washim",
    "JNV Yavatmal",
    "SEED",
  ],
  Bihar: [
    "JNV Aurangabad",
    "JNV Banka",
    "JNV Begusarai",
    "JNV Bhagalpur",
    "JNV Bhojpur",
    "JNV Buxar",
    "JNV Darbhanga",
    "JNV East Champaran",
    "JNV Gaya-1",
    "JNV Gaya-2",
    "JNV Gopalganj",
    "JNV Jamui",
    "JNV Jehanabad",
    "JNV Kaimur",
    "JNV Katihar",
    "JNV Khagaria",
    "JNV Kishanganj",
    "JNV Lakhi Sarai",
    "JNV Madhepura",
    "JNV Madhubani",
    "JNV Munger",
    "JNV Muzaffarpur",
    "JNV Nalanda",
    "JNV Nawada",
    "JNV Araria",
    "JNV Purnea",
    "JNV Patna",
    "JNV Rohtas",
    "JNV Saharsa",
    "JNV Samastipur",
    "JNV Saran",
    "JNV Shekhpura",
    "JNV Sheohar",
    "JNV Sitamarhi",
    "JNV Siwan",
    "JNV Supaul",
    "JNV Vaishali",
    "JNV West Champaran",
    "JNV Arwal",
  ],
  Jharkhand: [
    "JNV West Singhbhum",
    "JNV Bokaro",
    "JNV Chatra",
    "JNV Deoghar",
    "JNV Dhanbad",
    "JNV Dumka",
    "JNV East Singhbhum",
    "JNV Garhwa",
    "JNV Giridih",
    "JNV Godda",
    "JNV Gumla",
    "JNV Hazaribagh",
    "JNV Jamtara",
    "JNV Khunti",
    "JNV Koderma",
    "JNV Latehar",
    "JNV Lohardaga",
    "JNV Pakur-1",
    "JNV Pakur-2",
    "JNV Palamu-1",
    "JNV Palamu-2",
    "JNV Ramgarh",
    "JNV Ranchi",
    "JNV Sahibganj",
    "JNV Saraikela",
    "JNV Simdega",
  ],
  "West Bengal": [
    "JNV Bankura",
    "JNV Birbhum",
    "JNV Burdwan",
    "JNV Coochbehar",
    "JNV Darjeeling",
    "JNV East Medinipur",
    "JNV Hooghly",
    "JNV Howrah",
    "JNV Jalpaigudi",
    "JNV Murshidabad",
    "JNV Nadia",
    "JNV North 24 Parganas",
    "JNV Purulia",
    "JNV S.24 Parganas-1",
    "JNV S.24 Parganas-2",
    "JNV Uttar Dinajpur",
    "JNV West Medinipur",
    "JNV Dakshina Dinajpur",
    "JNV Alipurduar",
  ],
  "Andhra Pradesh": [
    "JNV Nellore",
    "JNV Prakasam-2",
    "JNV Srikakulam",
    "JNV Visakhapatnam",
    "JNV Vizianagaram",
    "JNV West Godavari",
    "JNV Kurnool",
    "JNV Nalgonda",
    "JNV Prakasam-1",
    "JNV Anantapur",
    "JNV Chittoor",
    "JNV East Godavari-1",
    "JNV East Godavari-2",
    "JNV Guntur",
    "JNV Kadapa",
    "JNV Krishna",
  ],
  "Andaman and Nicobar Islands": [
    "JNV Andaman & Nicobar",
    "JNV South Andaman",
    "JNV Car Nicobar",
  ],
  Karnataka: [
    "JNV Kalaburagi-1",
    "JNV Kodagu",
    "JNV Kolar",
    "JNV Koppal",
    "JNV Mandya",
    "JNV Mysore",
    "JNV Raichur",
    "JNV Ramanagara",
    "JNV Shimoga",
    "JNV Tumkur",
    "JNV North Canara",
    "JNV Yadgiri",
    "JNV Udupi",
    "JNV Bagalkot",
    "JNV Bangalore Rural",
    "JNV Bangalore Urban",
    "JNV Belagavi",
    "JNV Bellary",
    "JNV Bidar",
    "JNV Bijapur",
    "JNV Chamarajanagar",
    "JNV Chikkamagaluru",
    "JNV Chikkaballapura",
    "JNV Chitradurga",
    "JNV South Canara",
    "JNV Davangere",
    "JNV Dharwad",
    "JNV Gadag",
    "JNV Kalaburagi-2",
    "JNV Hassan",
    "JNV Haveri",
    "JNV Avanti",
  ],
  Kerala: [
    "JNV Alleppey",
    "JNV Ernakulum",
    "JNV Idukki",
    "JNV Kannur",
    "JNV Kasaragod",
    "JNV Kollam",
    "JNV Kottayam",
    "JNV Kozhikode",
    "JNV Malappuram",
    "JNV Palakkad",
    "JNV Pathanamthitta",
    "JNV Trivananthapuram",
    "JNV Thrissur",
    "JNV Wayanad",
  ],
  Lakshadweep: ["JNV Minicoy"],
  Pondicherry: ["JNV Karaikal", "JNV Mahe", "JNV Puducherry", "JNV Yanam"],
  Telangana: [
    "JNV Adilabad",
    "JNV Karimnagar",
    "JNV Khammam",
    "JNV Mahabubnagar",
    "JNV Medak",
    "JNV Nizamabad",
    "JNV Rangareddy",
    "JNV Warangal",
  ],
  Delhi: ["JNV North West Delhi", "JNV South West Delhi"],
  Haryana: [
    "JNV Ambala",
    "JNV Bhiwani",
    "JNV Faridabad",
    "JNV Fatehabad",
    "JNV Gurugram",
    "JNV Hissar",
    "JNV Jhajjar",
    "JNV Jind",
    "JNV Kaithal",
    "JNV Karnal",
    "JNV Kurukshetra",
    "JNV Mahendragarh",
    "JNV Nuh",
    "JNV Palwal",
    "JNV Panchkula",
    "JNV Panipat",
    "JNV Rewari",
    "JNV Rohtak",
    "JNV Sirsa",
    "JNV Sonepat",
    "JNV Yamuna Nagar",
  ],
  Rajasthan: [
    "JNV Ajmer",
    "JNV Alwar",
    "JNV Banswara-1",
    "JNV Banswara-2",
    "JNV Baran",
    "JNV Barmer",
    "JNV Bharatpur",
    "JNV Bhilwara",
    "JNV Bikaner",
    "JNV Bundi",
    "JNV Chittorgarh",
    "JNV Churu",
    "JNV Dausa",
    "JNV Dholpur",
    "JNV Hanumangarh",
    "JNV Jaipur",
    "JNV Jaisalmer",
    "JNV Jalore",
    "JNV Jhalawar",
    "JNV Jhunjhunu",
    "JNV Jodhpur",
    "JNV Karauli",
    "JNV Kota",
    "JNV Nagaur",
    "JNV Pali",
    "JNV Pratapgarh",
    "JNV Rajsamand",
    "JNV Sikar",
    "JNV Sirohi",
    "JNV Sriganganagar-1",
    "JNV Sriganganagar-2",
    "JNV Swai Madhopur",
    "JNV Tonk",
    "JNV Udaipur",
    "JNV Dungarpur",
  ],
};
